/*
 * Copyright (c) 2021 Intel Corporation.
 *
 * SPDX-License-Identifier: Apache-2.0
 * This code is reusing from /include/misc/util.h
 */

#define USER_APP_UTIL_EMPTY(...)
#define USER_APP_UTIL_DEFER(...) __VA_ARGS__ USER_APP_UTIL_EMPTY()
#define USER_APP_UTIL_OBSTRUCT(...) __VA_ARGS__ \
			 USER_APP_UTIL_DEFER(USER_APP_UTIL_EMPTY) ()
#define USER_APP_UTIL_EXPAND(...) __VA_ARGS__

#define USER_APP_UTIL_EVAL(...)  USER_APP_UTIL_EVAL1( \
		USER_APP_UTIL_EVAL1(USER_APP_UTIL_EVAL1(__VA_ARGS__)))
#define USER_APP_UTIL_EVAL1(...) USER_APP_UTIL_EVAL2( \
		USER_APP_UTIL_EVAL2(USER_APP_UTIL_EVAL2(__VA_ARGS__)))
#define USER_APP_UTIL_EVAL2(...) USER_APP_UTIL_EVAL3( \
		USER_APP_UTIL_EVAL3(USER_APP_UTIL_EVAL3(__VA_ARGS__)))
#define USER_APP_UTIL_EVAL3(...) USER_APP_UTIL_EVAL4( \
		USER_APP_UTIL_EVAL4(USER_APP_UTIL_EVAL4(__VA_ARGS__)))
#define USER_APP_UTIL_EVAL4(...) USER_APP_UTIL_EVAL5( \
		USER_APP_UTIL_EVAL5(USER_APP_UTIL_EVAL5(__VA_ARGS__)))
#define USER_APP_UTIL_EVAL5(...) __VA_ARGS__

#define USER_APP_UTIL_CAT(a, ...) USER_APP_UTIL_PRIMITIVE_CAT(a, __VA_ARGS__)
#define USER_APP_UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__

#define USER_APP_UTIL_INC(x) USER_APP_UTIL_PRIMITIVE_CAT(USER_APP_UTIL_INC_, x)
#define USER_APP_UTIL_INC_0 1
#define USER_APP_UTIL_INC_1 2
#define USER_APP_UTIL_INC_2 3
#define USER_APP_UTIL_INC_3 4
#define USER_APP_UTIL_INC_4 5
#define USER_APP_UTIL_INC_5 6
#define USER_APP_UTIL_INC_6 7
#define USER_APP_UTIL_INC_7 8
#define USER_APP_UTIL_INC_8 9
#define USER_APP_UTIL_INC_9 10
#define USER_APP_UTIL_INC_10 11
#define USER_APP_UTIL_INC_11 12
#define USER_APP_UTIL_INC_12 13
#define USER_APP_UTIL_INC_13 14
#define USER_APP_UTIL_INC_14 15
#define USER_APP_UTIL_INC_15 16
#define USER_APP_UTIL_INC_16 17
#define USER_APP_UTIL_INC_17 18
#define USER_APP_UTIL_INC_18 19
#define USER_APP_UTIL_INC_19 19

#define USER_APP_UTIL_DEC(x) USER_APP_UTIL_PRIMITIVE_CAT(USER_APP_UTIL_DEC_, x)
#define USER_APP_UTIL_DEC_0 0
#define USER_APP_UTIL_DEC_1 0
#define USER_APP_UTIL_DEC_2 1
#define USER_APP_UTIL_DEC_3 2
#define USER_APP_UTIL_DEC_4 3
#define USER_APP_UTIL_DEC_5 4
#define USER_APP_UTIL_DEC_6 5
#define USER_APP_UTIL_DEC_7 6
#define USER_APP_UTIL_DEC_8 7
#define USER_APP_UTIL_DEC_9 8
#define USER_APP_UTIL_DEC_10 9
#define USER_APP_UTIL_DEC_11 10
#define USER_APP_UTIL_DEC_12 11
#define USER_APP_UTIL_DEC_13 12
#define USER_APP_UTIL_DEC_14 13
#define USER_APP_UTIL_DEC_15 14
#define USER_APP_UTIL_DEC_16 15
#define USER_APP_UTIL_DEC_17 16
#define USER_APP_UTIL_DEC_18 17
#define USER_APP_UTIL_DEC_19 18
#define USER_APP_UTIL_DEC_20 19
#define USER_APP_UTIL_DEC_21 20
#define USER_APP_UTIL_DEC_22 21
#define USER_APP_UTIL_DEC_23 22
#define USER_APP_UTIL_DEC_24 23
#define USER_APP_UTIL_DEC_25 24
#define USER_APP_UTIL_DEC_26 25
#define USER_APP_UTIL_DEC_27 26
#define USER_APP_UTIL_DEC_28 27
#define USER_APP_UTIL_DEC_29 28
#define USER_APP_UTIL_DEC_30 29
#define USER_APP_UTIL_DEC_31 30
#define USER_APP_UTIL_DEC_32 31
#define USER_APP_UTIL_DEC_33 32
#define USER_APP_UTIL_DEC_34 33
#define USER_APP_UTIL_DEC_35 34
#define USER_APP_UTIL_DEC_36 35
#define USER_APP_UTIL_DEC_37 36
#define USER_APP_UTIL_DEC_38 37
#define USER_APP_UTIL_DEC_39 38
#define USER_APP_UTIL_DEC_40 39

#define USER_APP_UTIL_CHECK_N(x, n, ...) n
#define USER_APP_UTIL_CHECK(...) USER_APP_UTIL_CHECK_N(__VA_ARGS__, 0,)

#define USER_APP_UTIL_NOT(x) USER_APP_UTIL_CHECK( \
		USER_APP_UTIL_PRIMITIVE_CAT(USER_APP_UTIL_NOT_, x))

#define USER_APP_UTIL_NOT_0 ~, 1,

#define USER_APP_UTIL_COMPL(b) USER_APP_UTIL_PRIMITIVE_CAT( \
		USER_APP_UTIL_COMPL_, b)

#define USER_APP_UTIL_COMPL_0 1
#define USER_APP_UTIL_COMPL_1 0

#define USER_APP_UTIL_BOOL(x) USER_APP_UTIL_COMPL(USER_APP_UTIL_NOT(x))

#define USER_APP_UTIL_IIF(c) USER_APP_UTIL_PRIMITIVE_CAT(USER_APP_UTIL_IIF_, c)
#define USER_APP_UTIL_IIF_0(t, ...) __VA_ARGS__
#define USER_APP_UTIL_IIF_1(t, ...) t

#define USER_APP_UTIL_IF(c) USER_APP_UTIL_IIF(USER_APP_UTIL_BOOL(c))

#define USER_APP_UTIL_EAT(...)
#define USER_APP_UTIL_EXPAND(...) __VA_ARGS__
#define USER_APP_UTIL_WHEN(c) USER_APP_UTIL_IF(c) (USER_APP_UTIL_EXPAND, \
							USER_APP_UTIL_EAT)


#define USER_APP_UTIL_REPEAT(count, macro, ...)				 \
	USER_APP_UTIL_WHEN(count)					 \
	(								 \
		USER_APP_UTIL_OBSTRUCT(USER_APP_UTIL_REPEAT_INDIRECT) () \
		(							 \
			USER_APP_UTIL_DEC(count), macro, __VA_ARGS__	 \
		)							 \
		USER_APP_UTIL_OBSTRUCT(macro)				 \
		(							 \
			USER_APP_UTIL_DEC(count), __VA_ARGS__		 \
		)							 \
	)
#define USER_APP_UTIL_REPEAT_INDIRECT() USER_APP_UTIL_REPEAT

#define USER_APP_UTIL_LISTIFY(LEN, F, F_ARG) USER_APP_UTIL_EVAL( \
					USER_APP_UTIL_REPEAT(LEN, F, F_ARG))
