# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: intel_public_github
      url-base: https://github.com/intel

  #
  # Please add items below based on alphabetical order
  projects:
    - name: sedi-drivers
      path: modules/hal/sedi
      revision: pse
      remote: intel_public_github
    - name: zephyr
      path: zephyr
      revision: intel-pse
      remote: intel_public_github
      import:
        name-whitelist:
          - mbedtls
          - cmsis
    - name: rtos-if-drivers
      revision: zephyr-pse
      path: zephyr-iotg
      remote: intel_public_github
  self:
    path: ehl_pse-fw
