# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: iotg
      url-base: https://github.com/ganapathichinnu/
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: pse
      url-base: https://github.com/ganapathichinnu/

  #
  # Please add items below based on alphabetical order
  projects:
    - name: os.rtos.zephyr.iot.hal-intel
      revision: master
      remote: iotg
      path: modules/hal/intel
    - name: firmware.ec.pse.bootloader
      revision: master
      remote: pse
      path: modules/bootloader
    - name: firmware.ec.pse.cmsis
      revision: master
      remote: pse
      path: modules/interface/cmsis
    - name: firmware.ec.pse.baremetal
      revision: bm_zephyr_2px
      remote: pse
      path: modules/baremetal
    - name: os.rtos.zephyr.iot.zephyr
      path: zephyr
      revision: pse_base_changes
      remote: iotg
      import:
        name-whitelist:
          - mbedtls
          - cmsis
    - name: os.rtos.zephyr.iot.zephyr-iotg
      revision: master
      path: zephyr-iotg
      remote: iotg
  self:
    path: ehl_pse-fw
